services:
  - type: web
    name: cold-mail-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: os.getenv("GROQ_API_KEY")
        sync: false
